### ISSUE TITLE
Get data from Leetcode (leetcode.com)

### ISSUE THREAD

**Issue by diyao666** [diyao666/SI507_FinalProject#2]
1. Scraping with BeautifulSoup from leetcode.com and the scrapped data is relevant to the information about exercise questions from three different question categories. For instance, the **category**, **title**, **acceptance rate** and **difficulty level** for each of the first 50 **Algorithms** questions(OR **Database**, **System Desgin**) .  
2. Borrow the codes from **SI507Project5 (cache_contents.json)** to build the simple cache system

**Comment by anandpdoshi** [comment]
Looks like an interesting project. Have you tried scraping it? I looked at Problems page and it looks like the table is dynamically generated. You might have to use their internal undocumented API: https://leetcode.com/api/problems/all/ — I found it by exploring the Network tab of the browser's devtools.
